### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by chetanjain2099** [vishaltelangre/music-dl#10]
![untitled](https://user-images.githubusercontent.com/10224177/29674547-19d14de0-8910-11e7-8888-3b79e71378a4.png)

**Comment by vishaltelangre** [comment]
You need `ffmpeg` to be installed on your system.
http://www.ffmpeg.org/download.html

Let me know if the issue still persists.

**Comment by chetanjain2099** [comment]
I downloaded it and set its path in environment variable also but it shows same error.

**Comment by vishaltelangre** [comment]
From the above screenshot, I see following.

You tried to install `ffmpeg` using npm which I think won't work. As far as I know, `ffmpeg` isn't a NPM package. That's why it (i.e. npm) threw "Error: Cannot find ffmpeg" error. 

You need to install it from http://www.ffmpeg.org/download.html for Windows.

**Comment by chetanjain2099** [comment]
I have tried both method, it doesn't work. I downloaded using the the above link and extracted in C:\ffmpeg and set PATH=C:\ffmpeg\bin . But it doesn't work.

**Comment by AmitKKhanchandani** [comment]
Install Node.js
Download FFmpeg from http://ffmpeg.zeranoe.com/builds/ and extract the files to C:\ffmpeg
Set your **System Path Variable** to C:\ffmpeg\bin
Open Command Prompt - > npm install -g music-dl
Usage:- https://github.com/vishaltelangre/music-dl#usage

**Comment by vishaltelangre** [comment]
@chetanjain2099 Please see @AmitKKhanchandani's comment above.

If it works for you, we can make those instructions to be part of README document.

**Comment by chetanjain2099** [comment]
Still not working. I have added all the things you said shown in this image and its still doesn't work.
![untitled](https://user-images.githubusercontent.com/10224177/29728459-9ba89f54-89f5-11e7-994c-3fd22d7d118f.png)

**Comment by vishaltelangre** [comment]
I have no access to a Windows machine, so I cannot really check this right now. 

Maybe, see if you can use `ffmpeg` command alone? Also, try reinstalling `music-dl`. This (i.e. `music-dl`) utility heavily depends on https://github.com/fluent-ffmpeg/node-fluent-ffmpeg NPM package of which, `ffmpeg` is the only dependency.

Meanwhile, I am reopening this issue.

**Comment by AmitKKhanchandani** [comment]
@chetanjain2099 Make change on the System Variable (PATH), not on the User Variable (PATH), will be posting the screenshots from my pc in few minutes

**Comment by AmitKKhanchandani** [comment]
![capture](https://user-images.githubusercontent.com/11069057/29856008-a2b91302-8d6d-11e7-8669-eecf1fd4e712.JPG)

**Comment by varunchopra** [comment]
Keep the ffmpeg binary in the same folder as the node project and try.

**Comment by Aravinth-Shanmugam** [comment]
First i tried in windows cmd,  there i faced the erro message.
Later i tried in Node cmd, and it is working fine there.

**Comment by abhi1109** [comment]
Same Problem in Windows CMD. Tried many things but none of them worked out. Then switched to NODE CMD and it's working like a charm. 👍 :)

**Comment by vishaltelangre** [comment]
Cool.
