### ISSUE TITLE
Cannot find ffmpeg [Unhandled Error Event]

### ISSUE THREAD

**Issue by Aravinth-Shanmugam** [vishaltelangre/music-dl#14]
![music-dl error](https://user-images.githubusercontent.com/10824036/33239863-563178b8-d2d1-11e7-9d5c-e880cd466abe.png)

Retriving the complete list, but downloading only the filst file in mp4 format !

**Comment by vishaltelangre** [comment]
You need to have `ffmpeg` installed on your system. Please go through the suggested solutions on https://github.com/vishaltelangre/music-dl/issues/10.
