### ISSUE TITLE
ERROR: Error: Could not extract signature deciphering actions on gana.com

### ISSUE THREAD

**Issue by livetvbox** [vishaltelangre/music-dl#16]
try this 
music-dl http://gaana.com/album/aashiqui
and below error
ERROR: Error: Could not extract signature deciphering actions

**Comment by vishaltelangre** [comment]
@livetvbox Thank you for reporting this bug. I have fixed it in a new release v0.0.6.

Please update using `npm install -g music-dl` and try again.
