### ISSUE TITLE
Installation fails with the following errors

### ISSUE THREAD

**Issue by santanu-tripathy** [vishaltelangre/music-dl#18]
$npm install -g music-dl
npm ERR! code ETARGET
npm ERR! notarget No matching version found for libxmljs-dom@~0.0.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'osmosis'
npm ERR! notarget 

I am using Ubuntu 16.04LTS 64 bit OS

**Comment by vishaltelangre** [comment]
Thanks, @santanu-tripathy for reporting.

This has been caused due to https://github.com/libxmljs/libxmljs-dom/issues/6.

It will be automatically fixed once author of `libxmljs-dom` package releases `0.0.11` which another dependency `osmosis` needs.

**Comment by vishaltelangre** [comment]
Please retry, should be fixed now.
