### ISSUE TITLE
Cannot find module 'm3u8stream/lib/parse-time' on new installation (unable to download any music)

### ISSUE THREAD

**Issue by AmitKKhanchandani** [vishaltelangre/music-dl#26]
Node: 12.13.0
npm: 6.12.0

Error Screenshot:
![image](https://user-images.githubusercontent.com/11069057/71552884-d217f580-2a2a-11ea-837f-a3e78af280c2.png)

**Comment by hyndraslic** [comment]
Sam issue, hopefully gets fixed

**Comment by vishaltelangre** [comment]
This issue is fixed in the latest v0.0.8 version.

Please update using the `npm install -g music-dl` command.

If it still persists, please reopen this issue.
