### ISSUE TITLE
audio codec with ffprobe

### ISSUE THREAD

**Issue by ra312** [vishaltelangre/music-dl#29]
When trying to use music-dl with this url
$ music-dl -u https://www.youtube.com/watch\?v\=fTZgwpIvzC0
ERROR:   Reason: image not found
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Is this expected behaviour? Can we modify the code ?

**Comment by vishaltelangre** [comment]
`music-dl` supports downloading songs from only https://www.jiosaavn.com and https://gaana.com at this moment.

To download songs from YouTube directly, you can try https://github.com/ytdl-org/youtube-dl.
